name: Trigger auto deployment for emotibit-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/emotibit-api-AutoDeployTrigger-d27be2c5-6aeb-4150-bbbb-caade93b6671.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.EMOTIBITAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.EMOTIBITAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.EMOTIBITAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: "/Dockerfile"
          registryUrl: emotibitapiregistry.azurecr.io
          registryUsername: ${{ secrets.EMOTIBITAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.EMOTIBITAPI_REGISTRY_PASSWORD }}
          containerAppName: emotibit-api
          resourceGroup: Stress_Detection_Project
          imageToBuild: emotibitapiregistry.azurecr.io/emotibit-api:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


